controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

test2:
    path: /test2
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\testController::test2
